### PR TITLE
Update to Tokio 1.0

### LINKED ISSUE #24: Tokio 1.0
https://github.com/tokio-rs/tokio/releases/tag/tokio-1.0.0

### PR DESCRIPTION
**Pull request by BlackHoleFox**
I also updated some other deps minor versions and bumped `darkredis` to `0.8.1-dev` since Tokio was bumped to a new major version.

Resolves https://github.com/Bunogi/darkredis/issues/24

### CODE REVIEW

**Comment by vicky5124** [comment]
Is this ever going to get merged?

**Comment by insanitybit** [comment]
Also wondering - is there something blocking this from being merged in? This is the last dependency I need updated to migrate to tokio 1.0.

**Comment by vicky5124** [comment]
@insanitybit for now you can do this
```toml
[dependencies.darkredis]
git = "https://github.com/BlackHoleFox/darkredis"
branch = "tokio-and-dependency-updates"
```

**Comment by Bunogi** [comment]
Looks good to me. I'll merge this and make a release after ensuing the versions are still the latest version.

This new release will probably be the last(unless someone forks it), as I've been neglecting this project for a while. Sorry about that, but I just don't have the motivation to work on this anymore after getting a job and newer, shinier projects.

**Comment by BlackHoleFox** [comment]
@Bunogi Would you be interested in transferring the crate to someone willing to handle the routine maintenance for it? It has a nice API compared to the other Redis crates and it would be sad to see it die.

**Comment by Bunogi** [comment]
@BlackHoleFox I've been thinking about this, and I'm not against it in principle, but I've seen it go wrong several times. I don't think I'm comfortable doing that, unfortunately.

**Comment by BlackHoleFox** [comment]
@Bunogi Sure, that's 100% your call. I guess I'm on the opposite side, having seen a few where it's gone right. The most notable I've seen in recent is [the imgui-rs project](https://github.com/imgui-rs/imgui-rs/issues/392) changing maintainers.

The notify crate [also had a good success](https://github.com/orgs/notify-rs/people) changing hands.

**Pull request merged**
